#!/usr/bin/env python3
"""Build pose-reranker training rows from DB5.5 or user docking manifests.

Input CSV schema for user datasets:

case_id,receptor_path,ligand_path,native_complex_path,receptor_chains,ligand_chains

Paths may be absolute, relative to the manifest file, or relative to the
project root for manifests generated by the bundled DB5.5 collector.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Sequence

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from docking.docking import ProteinDocker
from docking.geometry import euler_to_matrix
from docking.metrics import evaluate_complex
from docking.ml_reranker import pose_feature_dict
from docking.scoring import DockingPose
from docking.structure import (
    PDBParser,
    ProteinStructure,
    clone_structure,
    extract_structure_by_chains,
    merge_structures,
)


@dataclass(frozen=True)
class TrainingCase:
    case_id: str
    receptor_path: Path
    ligand_path: Path
    native_complex_path: Path
    receptor_chains: List[str]
    ligand_chains: List[str]
    category: str = ""


def build_rows(args: argparse.Namespace) -> None:
    manifest_path = Path(args.manifest)
    cases = load_cases(manifest_path)
    if args.limit:
        cases = cases[: args.limit]
    if not cases:
        raise SystemExit(f"No usable cases found in {manifest_path}")

    output_path = Path(args.out)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    run_dir = Path(args.run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)

    docker = ProteinDocker(Path(args.config) if args.config else PROJECT_ROOT / "config.yaml")
    docker.top_n = args.top_n
    if args.disable_reranker:
        docker.pose_reranker = None
    if args.blind:
        docker.include_input_pose = False
        docker.input_pose_bonus = 0.0
    if args.rotations is not None:
        docker.coarse_rotations = args.rotations
    if args.mc_iterations is not None:
        docker.mc_iterations = args.mc_iterations

    rows = []
    rng = np.random.default_rng(args.seed)
    for index, case in enumerate(cases, 1):
        print(f"[{index}/{len(cases)}] building {case.case_id}", flush=True)
        case_out = run_dir / safe_name(case.case_id)
        try:
            native = PDBParser.parse(case.native_complex_path)
            native_receptor = extract_structure_by_chains(
                native,
                case.receptor_chains,
                name=f"{case.case_id}_native_receptor",
            )
            native_ligand = extract_structure_by_chains(
                native,
                case.ligand_chains,
                name=f"{case.case_id}_native_ligand",
            )
            if args.include_native_pose:
                rows.append(
                    pose_row_from_parts(
                        case,
                        native,
                        native_receptor,
                        native_ligand,
                        docker,
                        0,
                        "native_bound",
                    )
                )
            for jitter_index in range(args.native_jitters):
                jittered = jitter_ligand(native_ligand, rng, jitter_index)
                rows.append(
                    pose_row_from_parts(
                        case,
                        native,
                        native_receptor,
                        jittered,
                        docker,
                        jitter_index + 1,
                        "native_jitter",
                    )
                )
            if args.synthetic_decoys:
                receptor = PDBParser.parse(case.receptor_path)
                ligand = PDBParser.parse(case.ligand_path)
                for decoy_index in range(args.synthetic_decoys):
                    decoy_ligand = random_surface_decoy(
                        receptor,
                        ligand,
                        rng,
                        decoy_index,
                    )
                    rows.append(
                        pose_row_from_parts(
                            case,
                            native,
                            receptor,
                            decoy_ligand,
                            docker,
                            decoy_index + 1,
                            "synthetic_decoy",
                        )
                    )
            if not args.skip_docking:
                poses, _, _ = docker.dock(
                    case.receptor_path,
                    case.ligand_path,
                    case_out if args.save_docking_results else None,
                    receptor_chains=case.receptor_chains,
                    ligand_chains=case.ligand_chains,
                )
                for pose in poses:
                    rows.append(row_from_pose(case, native, pose))
        except Exception as exc:
            print(f"  skipped {case.case_id}: {exc}", file=sys.stderr)

    if not rows:
        raise SystemExit("No training rows were generated")
    pd.DataFrame(rows).to_csv(output_path, index=False)
    print(f"Wrote {len(rows)} pose training rows to {output_path}")


def pose_row_from_parts(
    case: TrainingCase,
    native: ProteinStructure,
    receptor: ProteinStructure,
    ligand: ProteinStructure,
    docker: ProteinDocker,
    rank: int,
    provenance: str,
) -> dict:
    pose = DockingPose(
        rank=rank,
        scores=docker.scorer.score_complex(receptor, ligand),
        ligand_coords=ligand.coords.copy(),
        complex_structure=merge_structures(receptor, ligand),
        provenance=provenance,
    )
    return row_from_pose(case, native, pose)


def jitter_ligand(ligand: ProteinStructure, rng: np.random.Generator, index: int) -> ProteinStructure:
    rotation_degrees = min(18.0, 3.0 + index * 3.0)
    translation_scale = min(8.0, 1.0 + index * 1.5)
    angles = np.deg2rad(rng.normal(0.0, rotation_degrees, size=3))
    rotation = euler_to_matrix(float(angles[0]), float(angles[1]), float(angles[2]))
    translation = rng.normal(0.0, translation_scale, size=3)
    return transformed_ligand(
        ligand,
        rotation,
        translation,
        name=f"{ligand.name}_jitter_{index}",
    )


def random_surface_decoy(
    receptor: ProteinStructure,
    ligand: ProteinStructure,
    rng: np.random.Generator,
    index: int,
) -> ProteinStructure:
    direction = rng.normal(size=3)
    norm = float(np.linalg.norm(direction))
    if norm == 0.0:
        direction = np.array([1.0, 0.0, 0.0])
    else:
        direction = direction / norm
    receptor_radius = structure_radius(receptor)
    ligand_radius = structure_radius(ligand)
    offsets = (-10.0, -4.0, 4.0, 10.0)
    center_distance = max(5.0, receptor_radius + ligand_radius + offsets[index % len(offsets)])
    target_center = receptor.center + direction * center_distance
    angles = rng.uniform(0.0, 2.0 * np.pi, size=3)
    rotation = euler_to_matrix(float(angles[0]), float(angles[1]), float(angles[2]))
    rotated = transformed_ligand(
        ligand,
        rotation,
        np.zeros(3),
        name=f"{ligand.name}_synthetic_decoy_{index}",
    )
    translation = target_center - rotated.center
    rotated.transform(np.eye(3), translation)
    return rotated


def transformed_ligand(
    ligand: ProteinStructure,
    rotation: np.ndarray,
    translation: np.ndarray,
    name: str,
) -> ProteinStructure:
    transformed = clone_structure(ligand, name=name)
    center = ligand.center
    for atom in transformed.atoms:
        atom.coords = rotation @ (atom.coords - center) + center + translation
    return transformed


def structure_radius(structure: ProteinStructure) -> float:
    if not structure.atoms:
        return 0.0
    return float(np.max(np.linalg.norm(structure.coords - structure.center, axis=1)))


def row_from_pose(
    case: TrainingCase,
    native: ProteinStructure,
    pose: DockingPose,
) -> dict:
    quality = (
        evaluate_complex(
            native,
            pose.complex_structure,
            case.receptor_chains,
            case.ligand_chains,
        )
        if pose.complex_structure is not None
        else None
    )
    return {
        "case_id": case.case_id,
        "category": case.category,
        "pose_rank": pose.rank,
        "provenance": pose.provenance,
        "capri_class": quality.capri_class if quality else "not_available",
        "lrmsd": quality.lrmsd if quality else None,
        "irmsd": quality.irmsd if quality else None,
        "fnat": quality.fnat if quality else None,
        "dockq": quality.dockq if quality else None,
        "acceptable": int(
            bool(quality)
            and quality.capri_class in {"acceptable", "medium", "high"}
        ),
        **pose_feature_dict(pose),
    }


def load_cases(manifest_path: Path) -> List[TrainingCase]:
    manifest_path = Path(manifest_path)
    if manifest_path.suffix.lower() == ".json":
        with open(manifest_path, encoding="utf-8") as handle:
            payload = json.load(handle)
        raw_cases = payload.get("cases", payload if isinstance(payload, list) else [])
    else:
        with open(manifest_path, encoding="utf-8", newline="") as handle:
            raw_cases = list(csv.DictReader(handle))

    base_dir = manifest_path.parent
    cases = []
    for row in raw_cases:
        receptor_path = resolve_path(row.get("receptor_path", ""), base_dir)
        ligand_path = resolve_path(row.get("ligand_path", ""), base_dir)
        native_path = resolve_path(
            row.get("native_complex_path") or row.get("bound_pdb_path", ""),
            base_dir,
        )
        if not receptor_path.exists() or not ligand_path.exists() or not native_path.exists():
            continue
        case_id = row.get("case_id") or row.get("complex_id") or native_path.stem
        receptor_chains = parse_chain_ids(row.get("receptor_chains", ""))
        ligand_chains = parse_chain_ids(row.get("ligand_chains", ""))
        if not receptor_chains:
            receptor_chains = sorted(PDBParser.parse(receptor_path).chains)
        if not ligand_chains:
            ligand_chains = sorted(PDBParser.parse(ligand_path).chains)
        cases.append(
            TrainingCase(
                case_id=str(case_id),
                receptor_path=receptor_path,
                ligand_path=ligand_path,
                native_complex_path=native_path,
                receptor_chains=receptor_chains,
                ligand_chains=ligand_chains,
                category=str(row.get("category", "")),
            )
        )
    return cases


def resolve_path(value: str, base_dir: Path) -> Path:
    path = Path(str(value))
    if path.is_absolute():
        return path
    for candidate in (base_dir / path, path, PROJECT_ROOT / path):
        if candidate.exists():
            return candidate.resolve()
    return (base_dir / path).resolve()


def parse_chain_ids(value: str | Iterable[str]) -> List[str]:
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return []
        if "," in text:
            return [item.strip() for item in text.split(",") if item.strip()]
        if " " in text:
            return [item.strip() for item in text.split() if item.strip()]
        return list(text)
    return [str(item) for item in value]


def safe_name(value: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in value)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", required=True, help="CSV/JSON case manifest")
    parser.add_argument("--out", required=True, help="Output pose training CSV")
    parser.add_argument("--config", help="Docking config path")
    parser.add_argument("--run-dir", default="results/pose_training_runs")
    parser.add_argument("--top-n", type=int, default=10)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--blind", action="store_true", help="Disable input-pose prior")
    parser.add_argument("--skip-docking", action="store_true", help="Only generate native/synthetic rows")
    parser.add_argument(
        "--disable-reranker",
        action="store_true",
        help="Do not use any configured pose reranker while generating docking decoys",
    )
    parser.add_argument(
        "--save-docking-results",
        action="store_true",
        help="Write per-case docking pose files while building training rows",
    )
    parser.add_argument(
        "--include-native-pose",
        action="store_true",
        help="Add one scored bound-native positive pose per case",
    )
    parser.add_argument(
        "--native-jitters",
        type=int,
        default=0,
        help="Add this many small perturbations around each bound-native ligand",
    )
    parser.add_argument(
        "--synthetic-decoys",
        type=int,
        default=0,
        help="Add this many random rigid-body unbound decoys per case",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--rotations", type=int, help="Override rotation samples")
    parser.add_argument("--mc-iterations", type=int, help="Override MC iterations")
    parser.set_defaults(func=build_rows)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
